"""Five profession guides cleared for editorial review; inheritance remains held."""
PROFESSION_GUIDES = {
'business-owner': '''
<h2>Start with the business and household together</h2>
<p>A business owner can look wealthy on paper and still have little room to absorb a bad quarter. Revenue is not take-home pay, and a valuation is not spendable cash. Map business cash, personal reserves, debt guarantees, insurance, retirement accounts, and ownership interests on one page. Then ask what happens if sales fall, a partner leaves, or a buyer delays an exit. A useful advisor will not merely propose a portfolio; they will explain where the business creates concentration and where outside savings can make the household less dependent on a single outcome.</p>
<p>Bring recent financial statements, a rough ownership chart, existing retirement-plan documents, business and personal insurance, debt guarantees, and a household spending estimate to an initial conversation. You need not upload sensitive records to a directory. Use the list to see whether a prospective advisor asks the right questions, and share documents only through a channel you trust after deciding to work together.</p>
<h2>Choose an advisor for the actual decision in front of you</h2>
<p>Not every owner needs the same specialist. A growing company may need compensation and retirement-plan design; a partner-owned company may need buy-sell coordination; a founder close to a transaction may need an exit team. Ask for examples of the advisor's work with businesses like yours, without asking them to disclose another client's confidential details. Find out whether they coordinate with your CPA and business attorney, who owns the action list, and how advice to the company differs from advice to you personally.</p>
<ul><li><strong>Before a sale:</strong> ask how the advisor models after-tax proceeds, debt payoff, earnouts and a plan B if the transaction fails.</li><li><strong>During growth:</strong> ask how to build liquid wealth outside the business while keeping enough operating runway.</li><li><strong>With partners:</strong> ask how the adviser coordinates ownership, succession and insurance questions with counsel rather than drafting legal documents.</li><li><strong>With employees:</strong> ask what retirement-plan options fit payroll, eligibility and the owner's own savings goals. A one-participant 401(k) has distinct eligibility limits; do not assume every owner can use one.</li></ul>
<h2>Separate business reinvestment from personal security</h2>
<p>A recurring planning error is putting every surplus dollar back into the company and treating a future sale as the whole retirement plan. The company may be the best growth opportunity, but it is also your income source, largest asset and often collateral for personal obligations. Set an explicit operating cash floor, a personal reserve, and a rule for moving money into diversified assets. The right amounts depend on margins, seasonality, debt covenants, household costs and the owner's risk capacity; a fixed percentage copied from another business is not a plan.</p>
<p>For retirement savings, compare employer-plan choices against employee costs and administration. The IRS describes options for self-employed people and the eligibility conditions for one-participant 401(k) plans. A tax adviser and plan administrator should verify the setup and contribution limits and estimated tax payments for the current tax year. See <a href="https://www.irs.gov/businesses/small-businesses-self-employed/estimated-taxes">IRS estimated-tax guidance</a>. <a href="https://www.irs.gov/retirement-plans/retirement-plans-for-self-employed-people">IRS: retirement plans for self-employed people</a>; <a href="https://www.irs.gov/retirement-plans/one-participant-401k-plans">IRS: one-participant 401(k) plans</a>.</p>
<h2>Plan the exit before there is a buyer</h2>
<p>Exit readiness is not a single valuation exercise. A buyer will care about transferable earnings, clean financials, customer concentration, key-person dependence, contracts, and how much of the operation can run without you. On the personal side, model several net-proceeds scenarios rather than multiplying revenue by a headline multiple. Transaction costs, taxes, debt, escrow, rollover equity and contingent payments can change the number available to support your life. Ask the advisor to show assumptions and coordinate the tax and legal structure with qualified specialists. If no sale occurs, the outside-wealth plan should still stand.</p>
<p>Some owners will ask about qualified small business stock, installment payments or trusts. Each depends on facts and timing; the wrong entity, shares, holding period or deal structure can change the result. Treat these as questions for a CPA and attorney before signing, not as benefits this directory promises. The IRS explains that a business sale can transfer multiple assets with different tax treatment: <a href="https://www.irs.gov/businesses/small-businesses-self-employed/sale-of-a-business">IRS: sale of a business</a>.</p>
<h2>Compare proposals in dollars and in responsibilities</h2>
<p>Ask each candidate for a written scope, full annual cost in dollars at your likely asset level, and what is excluded. An assets-under-management fee may cover investment management but not business valuation, plan administration or tax returns. A flat planning fee may not include transaction support. Ask whether the advisor or firm receives referral compensation, who holds your assets, and whether the person doing the planning is the person you will actually meet. Verify registration and review the firm's Form ADV, including services, fees, conflicts and disciplinary disclosures, through <a href="https://www.investor.gov/introduction-investing/getting-started/working-investment-professional/using-iapd">Investor.gov's IAPD guide</a>.</p>
<h2>A first-meeting checklist</h2>
<ol><li>What percentage of your work involves privately owned businesses at my stage?</li><li>What decisions will you own, and what goes to my CPA, lawyer or banker?</li><li>How would you test whether my retirement is overly dependent on a sale?</li><li>How will you model liquidity, taxes and risk if a sale is delayed or an earnout disappoints?</li><li>What do you charge in total, and when would that change?</li></ol>
<p>Valora lets you review independent advisor profiles and choose whom to contact. No advisor on this page is currently tagged as a business-owner specialist, so the profiles shown below are a general roster, not a verified specialist match. Ask each advisor directly whether they handle your situation. For a deeper educational primer, see <a href="/financial-advisor-for-business-owners/">financial advisors for business owners</a>.</p>
''',
'executive-professional': '''
<h2>Map your whole compensation, not just your salary</h2>
<p>A senior employee's financial picture can span cash pay, bonus, RSUs, options, deferred compensation, employer stock in a retirement plan, and benefits that change when a job changes. Write down each award's vest date, expiration or exercise window, withholding, trading restrictions and expected tax event. A good first meeting turns that schedule into a decision calendar, not a generic recommendation to hold or sell. Your employer's award agreements and plan documents control the terms; an advisor should read them before offering a timetable.</p>
<p>Also list household spending, emergency reserves, debt, outside investments and any financial dependence on the same employer through a spouse's job. That shows how much risk is already tied to one company before a single share is sold or retained. Investor.gov explains the difference between allocating across asset classes and diversifying within them: <a href="https://www.investor.gov/introduction-investing/getting-started/asset-allocation">asset allocation and diversification</a>.</p>
<h2>What an executive-focused advisor should be able to handle</h2>
<ul><li><strong>Equity compensation:</strong> model vesting, withholding and a deliberate concentration limit; distinguish RSUs, restricted stock, ISOs, NSOs and ESPP shares rather than treating them alike.</li><li><strong>Bonus and deferred pay:</strong> place elections on a calendar before irrevocable deadlines; compare tax timing with employer-credit risk and payout restrictions.</li><li><strong>Job change:</strong> reconcile option exercise periods, insurance gaps, retirement-plan rollovers, severance, relocation and blackout windows.</li><li><strong>Retirement:</strong> test whether savings outside employer stock support the target date even if the company's share price falls sharply.</li></ul>
<p>Ask for an example work product with private information removed: a vesting calendar, a tax-year scenario comparison, or a concentration dashboard. The answer should name which decisions require your CPA, benefits team or securities counsel. An advisor should not imply that a projected tax outcome is guaranteed.</p>
<h2>Equity and taxes: the timing is the strategy</h2>
<p>RSUs generally create wage income when they vest; selling later creates a separate capital gain or loss measured from the value included as income. Options can have very different tax results depending on type and exercise timing. Under-withholding is especially easy to miss when several awards and a bonus land in one year. Have a CPA review estimated payments and the actual award documents. A departure can shorten an option's exercise window, but that window is plan-specific: do not rely on a rule of thumb without checking yours. The <a href="https://www.irs.gov/taxtopics/tc427">IRS stock-options overview</a> distinguishes statutory and nonstatutory treatment; an ISO exercise may also matter for alternative minimum tax, so coordinate with your CPA.</p>
<p>Restricted stock and some early exercises raise the question of an 83(b) election, with a short statutory filing window and a risk of paying tax on value you never ultimately keep. This is a tax/legal decision, not a universal recommendation. The <a href="https://www.irs.gov/pub/irs-pdf/f15620.pdf">IRS Section 83(b) election form</a> is a starting reference; ask your tax adviser whether the election applies and what the current filing process requires.</p>
<h2>Decide how much employer risk the household can carry</h2>
<p>The same company's fortunes can determine your pay, bonus, unvested awards, vested shares and career prospects. Selling shares as they vest may reduce that concentration; holding them may be rational for some people, but the decision should be explicit. Compare a downside scenario, such as a large stock decline paired with job loss, to the goals the money funds. Trading windows, insider status, lockups, company policies and a potential 10b5-1 plan require legal and compliance review. An advisor should coordinate that review, not promise a trade can be made on demand.</p>
<h2>Ask about fees, conflicts and team coordination</h2>
<p>Get the proposed fee in annual dollars and ask whether it covers equity modeling, tax coordination and planning during a job change. If the adviser wants to manage your portfolio, find out whether planning is conditioned on transferring assets, and compare underlying fund costs. Ask who will work with your CPA, who will monitor the vesting calendar and who will call you before a deadline. Read Form ADV and check registration and disclosures using <a href="https://www.investor.gov/introduction-investing/getting-started/working-investment-professional/check-out-your-investment-professional">Investor.gov's professional-check guide</a>.</p>
<h2>Questions for the first call</h2>
<ol><li>Which forms of equity compensation have you handled, and what do you need from my award documents?</li><li>How would you combine compensation, tax estimates and household concentration on one timeline?</li><li>What can you do before a job change, and what must counsel or a CPA decide?</li><li>How do you price one-off planning versus ongoing management?</li><li>Who checks upcoming elections and exercise dates with me?</li></ol>
<p>Valora has not tagged an advisor specifically for executive or professional clients on this page. The profiles below are a general roster, not a vetted executive-specialist match. Ask each advisor about location and fit. Confirm experience directly. For employees with substantial tech equity, the separate <a href="/financial-advisor-for-tech-employees/">tech-employee guide</a> goes deeper.</p>
''',
'entrepreneur-founder': '''
<h2>Founders have two balance sheets</h2>
<p>Company ownership may be valuable but illiquid, and a funding round's price is not the cash you can use to pay a mortgage. Start with two views: household runway and company exposure. List accessible savings, base pay, debt, insurance, dependents and tax liabilities. Separately list shares, vesting, exercise costs, dilution, investor preferences and any guarantees. Then ask what the household can withstand if the company takes longer to exit or never reaches its last valuation. An advisor can help build a plan that lets you make company decisions without every month becoming a personal liquidity emergency.</p>
<p>Bring your cap table summary, grant and shareholder documents, recent tax returns and a simple spending estimate to a professional you choose. Do not disclose confidential company records to a directory or an unvetted stranger. A founder's counsel, company finance lead and personal tax adviser should agree on what information can be shared and who makes which decisions.</p>
<h2>Choose help for the company's stage</h2>
<ul><li><strong>At formation:</strong> ask counsel and a tax specialist to review entity structure, share issuance and any time-sensitive elections. The financial advisor can model household cash and risk, but cannot replace them.</li><li><strong>At fundraising:</strong> distinguish headline valuation from your economic ownership after dilution, vesting and liquidation preferences. Decide whether salary and cash reserves are adequate.</li><li><strong>At secondary liquidity:</strong> model proceeds after taxes, remaining exposure and any restrictions before deciding whether a partial sale improves resilience.</li><li><strong>At exit:</strong> plan tax reserves, concentrated proceeds, income replacement and an investment policy before the wire arrives.</li></ul>
<p>Ask candidates to walk through how their advice changes across stages. Someone who has only managed liquid portfolios may be useful later but not qualified to lead a complex pre-exit decision.</p>
<h2>Founder equity has deadlines and uncertainty</h2>
<p>Share classes, options and restricted stock have different legal and tax mechanics. An 83(b) election may be relevant to certain restricted property and has a strict filing window; it can also create tax cost even if the shares later lose value. The <a href="https://www.irs.gov/pub/irs-pdf/f15620.pdf">IRS Section 83(b) election form</a> helps frame the question, but filing is a specialist decision. Potential stock-sale tax treatment depends on company and shareholder facts, issuance and holding requirements, and current law. Do not plan an exit around a presumed exclusion without a written tax review of your own shares.</p>
<p>Options can also require cash to exercise and create tax obligations before liquidity. Add each vest, expiration and decision date to a shared timeline with your CPA and counsel. A reliable advisor should show an adverse scenario, not only a best-case IPO slide.</p>
<h2>Make diversification an explicit tradeoff</h2>
<p>Founders often hear that selling any shares shows weak conviction. But household security and company commitment are separate choices. If a permitted secondary sale is available, model the after-tax money that would cover years of personal needs and the upside you retain. Compare that with the risk of holding everything. If no sale is possible, build liquid investments from salary when feasible and keep essential insurance and reserves current. Investor.gov's <a href="https://www.investor.gov/introduction-investing/getting-started/asset-allocation">diversification guide</a> explains why owning one company, even a company you know intimately, does not spread portfolio risk.</p>
<h2>Screen the advisor and the fee</h2>
<p>Ask whether the advisor has worked with founders whose wealth was mostly private, whether they will coordinate with company counsel and your personal tax professional, and whether their fee structure works before there are assets to manage. A percentage-of-assets fee may be a poor fit for a pre-liquidity founder; a scoped planning fee may be easier to assess. Get scope and costs in writing. Verify registration, services, conflicts and disclosures through <a href="https://www.investor.gov/introduction-investing/getting-started/working-investment-professional/using-iapd">IAPD</a>.</p>
<h2>Five useful interview questions</h2>
<ol><li>How do you plan for a founder with high paper wealth and low liquid savings?</li><li>Which equity decisions do you handle, and when do CPA and counsel take the lead?</li><li>How would you model dilution, preferences, tax and delayed liquidity?</li><li>What would you recommend checking before a secondary sale, without assuming the sale is allowed?</li><li>What do I pay now, before a liquid exit, and what changes after one?</li></ol>
<p>No advisor here is currently tagged as a founder specialist. The profiles below are a general roster, not proof of founder-specific experience. Ask them directly about the decisions you face. The <a href="/financial-advisor-for-business-owners/">business-owner guide</a> covers related planning for privately owned firms.</p>
''',
'retired': '''
<h2>Retirement changes the job of the plan</h2>
<p>Before retirement, a paycheck replenishes savings. After retirement, withdrawals, Social Security, pensions and perhaps part-time work must support spending through uncertain markets and lifespans. The central question is not simply whether the portfolio can earn a target return. It is whether you can pay for essential needs in a bad early market, manage taxes across several account types, and adjust spending without losing the life you planned. A useful advisor should make those tradeoffs visible in numbers, not sell a universal withdrawal rule.</p>
<p>Bring a year of actual spending, expected housing and health costs, account balances by tax treatment, pension statements, insurance coverage and Social Security estimates. Separate must-pay expenses from travel, gifts and other spending you can flex. Update the list when a spouse retires, a parent needs care, a home is sold or health changes. A retirement plan is a set of decisions to revisit, not a projection printed once.</p>
<h2>Build income in layers</h2>
<p>List income you can count on, with start dates and inflation treatment: Social Security, pensions or annuities. Compare it with the essential spending floor. Then set a plan for the gap from cash reserves and investments, recognizing that near-term spending should not depend on selling volatile assets at a bad moment. A reserve can help, but holding too much in cash for decades can expose purchasing power to inflation. Ask an advisor to show the cost and risk of each layer, including an annuity's fees, insurer risk, liquidity restrictions and survivor benefits where relevant.</p>
<p>Withdrawal order matters. Taxable brokerage, traditional retirement accounts and Roth accounts are taxed differently. A rigid taxable-first rule can create a later tax spike when required distributions begin; a rigid tax-deferred-first rule may waste low-bracket years. Model alternatives with a tax professional using your own income, Medicare premiums and state rules. Check <a href="https://www.medicare.gov/basics/costs/medicare-costs">Medicare's current cost page</a> instead of relying on a static premium estimate. Check the current required minimum distribution rules rather than a recalled age: <a href="https://www.irs.gov/retirement-plans/retirement-plan-and-ira-required-minimum-distributions-faqs">IRS RMD FAQs</a>.</p>
<h2>Social Security is a household decision</h2>
<p>Claiming earlier generally reduces the monthly benefit compared with waiting, while delayed claiming can increase it up to age 70. But the right choice depends on health, work, cash needs, marriage, survivor benefits and the rest of the portfolio. Ask for a comparison that shows both spouses' lifetime income and what happens after the first death, not a single break-even age. SSA's <a href="https://www.ssa.gov/retirement/plan-for-retirement">retirement planner</a> provides personalized estimate tools and current claiming rules.</p>
<h2>Stress-test the risks that actually change a life</h2>
<ul><li><strong>Sequence risk:</strong> losses early in retirement can hurt more when withdrawals continue. Ask what spending changes, cash sources or rebalancing rules apply after a prolonged decline.</li><li><strong>Longevity:</strong> test the plan beyond average life expectancy, including one spouse living significantly longer.</li><li><strong>Inflation:</strong> show what happens if essential expenses rise faster than planned, particularly health care and housing.</li><li><strong>Care and family:</strong> model long-term care, support for relatives and the surviving spouse's own income and housing needs.</li><li><strong>Taxes:</strong> compare Roth conversions, charitable gifts and account withdrawals only after tax-year and Medicare effects are included.</li></ul>
<p>A single probability-of-success number hides assumptions. Ask to see the return, inflation, lifespan and spending inputs, and ask which decision changes when the model worsens. Review after major life events and at least when the spending plan changes.</p>
<h2>What to ask a retirement advisor</h2>
<ol><li>How do you turn my accounts into a monthly spending plan and update it in a downturn?</li><li>Will you compare Social Security and pension choices at the household level?</li><li>Who does the annual tax projection and coordinates with my CPA?</li><li>How do you handle long-term care and estate-document questions without practicing law or selling an unsuitable product?</li><li>What is the all-in cost in dollars, including investment funds and any insurance compensation?</li></ol>
<p>Verify an advisor's registration, fees, conflicts and disciplinary disclosures on <a href="https://www.investor.gov/introduction-investing/getting-started/working-investment-professional/using-iapd">Investor.gov's IAPD guide</a>. No advisor on this page is currently tagged as a retirement-client specialist, so the profiles below are a general roster, not a verified specialty match. Ask each one how they would address your needs. For a concrete scenario, start with the related <a href="/calculators/retirement/">retirement calculators</a>; they are illustrations, not personalized advice.</p>
''',
'recently-sold-a-business': '''
<h2>After closing, slow the next decision down</h2>
<p>A sale can turn one concentrated, illiquid asset into cash, escrow claims, earnout rights or rollover equity. The headline price is not the amount available to spend. Before changing your lifestyle or buying investments, reconcile the closing statement, debt repayment, deal fees, tax estimates, holdbacks, earnout terms and any retained ownership. Keep an accessible reserve for obligations that could arrive before the final tax return. Ask the transaction CPA what is owed and when; this page cannot calculate your tax bill.</p>
<p>Store the purchase agreement, allocation schedules, closing statement and supporting basis records securely. These are sensitive documents. A prospective advisor can describe the information they need before you share full files, and should use secure channels once engaged. The IRS explains that selling a business usually means disposing of different assets, each with distinct tax treatment: <a href="https://www.irs.gov/businesses/small-businesses-self-employed/sale-of-a-business">IRS: sale of a business</a>.</p>
<h2>Read the proceeds in their actual form</h2>
<ul><li><strong>Cash at closing:</strong> separate tax reserves, near-term household needs and investable capital.</li><li><strong>Escrow and holdbacks:</strong> do not count money subject to claims as available now.</li><li><strong>Earnouts:</strong> model zero, base and high outcomes; check the payment triggers and the risk that the buyer cannot or will not pay.</li><li><strong>Rollover equity:</strong> retained shares may remain concentrated, illiquid and subject to new governance terms.</li><li><strong>Installments:</strong> ask the CPA how recognition and risk work under your contract; <a href="https://www.irs.gov/publications/p537">IRS Publication 537</a> explains installment-sale rules generally, but your transaction may differ.</li></ul>
<p>Many structural tax choices happen before signing and cannot be reconstructed afterward. A post-close adviser should identify what remains open, not imply a guaranteed retroactive fix. If sale documents impose noncompete, employment or consulting obligations, a lawyer should interpret them.</p>
<h2>Replace the business's old jobs</h2>
<p>The business may have provided salary, insurance, a place to invest surplus cash and a future retirement plan. After the sale, the household needs each function independently. Start with annual after-tax spending, one-off commitments, health insurance, debt and family support. Compare that with reliable income, liquid after-tax proceeds and amounts still contingent. A portfolio withdrawal plan should survive low returns and delayed earnout payments. Decide what money is for near-term spending and what can tolerate long-term market risk.</p>
<p>An investment policy helps prevent a windfall from becoming dozens of unrelated purchases. Write down goals, target allocation, rebalancing rules, who may authorize changes, and how much single-company or private-investment exposure is acceptable. Moving everything into a portfolio in one day may be mathematically defensible in some circumstances; moving in stages can reduce regret for some people. The key is a deliberate plan with deadlines, not indefinite idle cash. Investor.gov explains <a href="https://www.investor.gov/introduction-investing/getting-started/asset-allocation">diversification and rebalancing</a>.</p>
<h2>Revisit legal and family documents</h2>
<p>An estate plan built around operating-company ownership may no longer fit. Have an estates attorney check wills or trusts, beneficiary designations, powers of attorney, business-related agreements and charitable goals. A planner can coordinate the financial consequences; only legal counsel should draft or interpret the documents. If a large cash balance temporarily sits at one institution, ask about the actual account ownership and applicable deposit insurance rather than assuming all balances are protected.</p>
<h2>Screen an advisor for post-exit work</h2>
<ol><li>Can you show how you model available cash separately from taxes, escrow, earnout and rollover equity?</li><li>Who coordinates with the deal CPA and estates attorney, and who maintains the action list?</li><li>How do you translate proceeds into a sustainable spending policy with bad-market scenarios?</li><li>What experience do you have with a comparable exit without revealing other clients?</li><li>What are your fees in annual dollars, including investment and referral compensation?</li></ol>
<p>Check registration and firm disclosures using <a href="https://www.investor.gov/introduction-investing/getting-started/working-investment-professional/check-out-your-investment-professional">Investor.gov</a>. Valora has no advisor specifically tagged for recently sold business clients on this page. The profiles below are a general roster, not proof of post-exit expertise. Ask each advisor about location and fit. Confirm fit directly. The <a href="/financial-advisor-for-business-owners/">business-owner guide</a> covers planning before an exit.</p>
''',
}
