# -*- coding: utf-8 -*-
"""Page-specific FAQs for /find-a-financial-advisor/ directory pages.

Each entry is a list of (question, answer) pairs rendered both as the
visible FAQ accordion and as the page's FAQPage JSON-LD, so the two can
never drift. Answers are grounded general education - no invented
statistics, no advisor-specific claims, and honest where the answer
depends on the person's situation.
"""

DIRECTORY_FAQS = {
    # ---------------- specialties ----------------
    "managing-investments": [
        ("What does an investment management advisor actually do?",
         "They build and maintain a portfolio matched to your goals, time horizon, and risk tolerance: asset allocation, fund selection, rebalancing, and tax-aware placement of investments across accounts. Most also coordinate the portfolio with the rest of your financial life rather than managing it in isolation."),
        ("How do investment advisors charge for managing money?",
         "The most common model is a percentage of assets under management, billed quarterly. Flat annual fees, hourly fees, and subscription models also exist. Ask for the full fee in dollars per year at your asset level, and whether fund expense ratios come on top."),
        ("What's the difference between a fiduciary advisor and a broker?",
         "A fiduciary is legally required to act in your best interest. Brokers historically operated under a suitability standard, though Regulation Best Interest has narrowed the gap. Ask any advisor directly: 'Are you a fiduciary at all times when working with me?' and get it in writing."),
        ("How much money do I need before an advisor will manage it?",
         "It varies widely. Some advisors have no minimum, others start at $250,000 or $1 million of investable assets, and some charge flat fees regardless of balance. If you're below a firm's minimum, ask whether they offer a different service tier."),
        ("Can I keep my current accounts if I hire an advisor?",
         "Usually your money moves to a custodian the advisor works with (a large independent custodian holds the assets in your name, not the advisor). You keep ownership throughout; the advisor gets trading authority, not ownership of the accounts."),
    ],
    "retirement-planning": [
        ("When should I start working with a retirement planning advisor?",
         "The highest-value moments are the five to ten years before retirement and the first few years after: that's when withdrawal strategy, Social Security timing, Roth conversions, and healthcare costs get locked in. Earlier is still useful, but the stakes concentrate around the transition."),
        ("What does a retirement plan from an advisor include?",
         "A projection of spending against income sources, a sustainable withdrawal rate, a Social Security and pension claiming strategy, tax planning across account types (traditional, Roth, taxable), Medicare and healthcare cost estimates, and a plan for the order you draw accounts down."),
        ("How much can I safely withdraw in retirement?",
         "The 4% rule is a starting point from 1990s research, not a guarantee. Your sustainable rate depends on your asset allocation, flexibility to adjust spending, other income sources, and the returns sequence you actually experience. An advisor stress-tests your specific plan rather than quoting a single number."),
        ("What's the difference between a Roth conversion and a regular withdrawal?",
         "A Roth conversion moves money from a traditional IRA to a Roth IRA: you pay income tax on the converted amount now, and qualified withdrawals later are tax-free. Conversions can make sense in low-income years, especially between retirement and required minimum distributions, but the right amount depends on your tax bracket each year."),
        ("Do I need a retirement advisor if I already have a 401(k)?",
         "A 401(k) is an account, not a plan. It doesn't decide when you can retire, how much you can spend, when to claim Social Security, or how to turn savings into income. An advisor coordinates those decisions, of which the 401(k) is just one input."),
    ],
    "selling-a-business": [
        ("When should I involve a financial advisor in selling my business?",
         "Ideally one to three years before a sale. Pre-sale planning - entity structure, QSBS eligibility where applicable, estate moves, and cleaning up financials - is far more valuable before a letter of intent than after. Many options genuinely expire at closing."),
        ("What should I do with the proceeds after selling my business?",
         "Common priorities: set aside the tax bill first, replace the income the business provided, diversify away from a single-asset concentration, and revisit estate documents with the new balance sheet. Most advisors recommend a deliberate pause before large commitments - the months right after a sale invite expensive mistakes."),
        ("How is the sale of a business taxed?",
         "It depends on deal structure: asset sale versus stock sale, installment payments, earnouts, and your entity type all change the answer, often materially. Long-term capital gains treatment is common for stock sales held over a year. This is a question for your CPA and deal attorney early, not after signing."),
        ("Do I need a wealth manager if I already have a business broker or M&A advisor?",
         "They do different jobs. A broker or M&A advisor sells the business; a wealth advisor plans what the sale means for your taxes, income, investments, and estate before and after the wire arrives. The two should work from the same timeline."),
        ("What is QSBS and could it apply to my sale?",
         "Qualified Small Business Stock (Section 1202) can exclude some or all federal gain on the sale of qualifying C-corp stock, subject to holding-period and other requirements that changed for newly issued stock in 2025. Whether your shares qualify is a fact-specific determination for a tax professional - confirm before you sell, not after."),
    ],
    "business-owner-wealth-planning": [
        ("How is wealth planning different when most of my net worth is my business?",
         "The core problem is concentration: your income, savings, and net worth all depend on one asset. Planning focuses on extracting value tax-efficiently over time, building wealth outside the business, protecting against key-person risk, and having an exit path even if you never use it."),
        ("Should I pay myself a salary or take distributions?",
         "For S-corp owners, reasonable compensation is a real IRS requirement, and the salary/distribution split has payroll tax consequences in both directions. The right mix depends on your entity type, profit level, and retirement plan strategy - set it with your CPA annually, not once."),
        ("What retirement accounts work best for business owners?",
         "Solo 401(k)s, SEP-IRAs, and cash balance plans allow much larger contributions than employee plans, especially with no or few employees. The best fit depends on headcount, income stability, and how much you want to shelter each year."),
        ("How do I separate personal and business finances cleanly?",
         "Separate accounts and cards, a documented salary or draw, clean books, and no personal expenses through the business. Beyond hygiene, it protects liability separation and makes the business sellable - buyers and lenders discount tangled finances."),
        ("What insurance does a business owner actually need?",
         "Beyond personal coverage: key-person life and disability insurance, a funded buy-sell agreement if you have partners, and liability coverage matched to your risks. The buy-sell is the one most often drafted and never funded - an unfunded agreement fails exactly when it's needed."),
    ],
    "tax-planning": [
        ("What's the difference between tax preparation and tax planning?",
         "Preparation reports what already happened. Planning changes what happens: timing income and deductions, choosing account types, harvesting losses, structuring conversions, and coordinating with your investment and estate decisions during the year, while there's still time to act."),
        ("Can a financial advisor do my taxes?",
         "Most advisors don't file returns - they plan alongside your CPA. Some firms have in-house tax professionals. The productive split: the advisor owns strategy and timing across your whole financial life, the CPA owns compliance and filing, and they talk to each other."),
        ("What tax strategies actually matter for high earners?",
         "Potential topics include retirement-account contributions, investment tax management, charitable giving, Roth conversions and equity-compensation timing. Eligibility, deadlines and tax effects depend on your account, income and current law. Ask a qualified tax professional to prioritize them for your circumstances."),
        ("When during the year should tax planning happen?",
         "Review your plan when income or circumstances change and before major deadlines. Year-end matters for some elections, but deadlines vary by account, transaction and tax year. Equity events, business sales and large bonuses deserve a discussion with your CPA before the decision."),
        ("How do I know if I'm overpaying in taxes?",
         "Ask a qualified tax professional to compare your return, withholding and estimated payments with your actual income, deductions and available elections. A projected tax saving depends on facts and current law; do not assume a single session can quantify or guarantee it."),
    ],
    "estate-planning": [
        ("What documents make up a basic estate plan?",
         "Depending on state law and family circumstances, an attorney may recommend a will, powers of attorney, health-care directives and possibly a trust. Review beneficiary designations on retirement accounts and insurance with counsel because they can direct transfer outside a will."),
        ("Do I need a trust or is a will enough?",
         "A revocable trust can help manage certain assets during incapacity and pass properly titled assets outside probate, but it does not automatically avoid every probate, tax or privacy issue. Whether it is useful depends on state law, assets and family goals. Ask an estates attorney to compare it with a will-based plan."),
        ("How often should an estate plan be updated?",
         "Review after major life or law changes, and periodically with counsel based on your circumstances."),
        ("What does a financial advisor do in estate planning if they don't draft documents?",
         "A financial advisor can maintain the asset inventory, model liquidity and survivor income, and coordinate account and beneficiary changes with an estates attorney and tax professional. The attorney should direct legal titling and document interpretation; do not assume a signed document alone changes an account."),
        ("How does estate tax work and should I worry about it?",
         "Federal estate tax depends on current law and the taxable estate, and state estate or inheritance taxes may also apply. Exemptions and rules change; ask an estate attorney and tax professional to review your location, assets and dates rather than relying on a static threshold here."),
    ],
    "concentrated-stock": [
        ("How much single-stock concentration is too much?",
         "Common planning guidelines flag any single position above 10-20% of investable assets, but the real question is what happens to your life if the stock falls by half. If your employer is also the source of your income, your true exposure is even higher than the position size suggests."),
        ("What are my options for reducing a concentrated position?",
         "Selling on a schedule, hedging strategies, exchange funds, charitable strategies like donating appreciated shares, and staged diversification plans. The right mix balances tax cost, concentration risk, blackout windows, and any insider-trading constraints like 10b5-1 plans."),
        ("How do I diversify without a huge tax bill?",
         "Spread sales across tax years, harvest losses elsewhere, donate appreciated shares to charity or a donor-advised fund, and prioritize selling the lots with the highest basis. A staged plan usually beats an all-at-once sale on taxes, even though it takes longer."),
        ("What is a 10b5-1 plan and do I need one?",
         "It's a pre-arranged trading plan that lets company insiders sell shares on a set schedule without regard to what they later learn. If you're an executive or have access to material non-public information, it's the standard, clean way to diversify - set it up with your company's compliance team."),
        ("Should I ever hold onto a concentrated position?",
         "Sometimes: if you have genuinely asymmetric information about long-term prospects, low basis with estate step-up ahead, or restrictions that make selling costly. But 'it's done well so far' is not a strategy - the decision to hold should be made deliberately, revisited regularly, and sized so a bad outcome doesn't change your life."),
    ],
    "inheritance-sudden-wealth": [
        ("What should I do first after receiving a large inheritance?",
         "Pause major discretionary commitments while confirming what you actually received, who controls it and which deadlines apply. Some account claims, property issues, tax filings and inherited-retirement distributions can be time-sensitive; ask the executor or trustee and qualified professionals before moving assets."),
        ("Do I owe taxes on an inheritance?",
         "Receiving property is not the same tax event as later income or a sale. Estate, state inheritance, retirement-account and asset-basis rules can differ by asset, beneficiary and location. A CPA and estates attorney should review your documents; do not assume the inheritance or later distributions are tax-free."),
        ("What are the rules for an inherited IRA?",
         "Distribution rules depend on the account, beneficiary relationship, date of death and whether the owner had begun required distributions. Some beneficiaries face a ten-year deadline and may have annual requirements. Ask a tax professional to check the current IRS Publication 590-B for your specific account and year."),
        ("How do I invest a sudden lump sum?",
         "First separate tax reserves and near-term spending from money meant for long-term investing. A lump-sum or staged approach has different market and behavioral risks; ask an advisor to compare them against your goals and ability to stay invested through a downturn."),
        ("Do I need an advisor for an inheritance, or can I manage it myself?",
         "An advisor may be worth considering when inherited assets interact with trusts, retirement accounts, business interests or family decisions. Compare the scope, fees and credentials of any professional before deciding whether to hire one; many people manage simpler inheritances on their own."),
    ],
    "cash-liquidity-management": [
        ("How much cash should I keep?",
         "A common baseline is three to six months of expenses as an emergency reserve, plus known spending due within two to three years (taxes, tuition, a home purchase). Beyond that, large cash balances lose ground to inflation and usually belong in investments matched to your timeline."),
        ("Where should I keep cash so it actually earns something?",
         "High-yield savings accounts, money market funds, Treasury bills, and CDs are the standard options, differing in access, rate, and insurance coverage. Spreading cash across account types can keep balances within FDIC or SIPC limits while capturing competitive rates."),
        ("Are money market funds safe?",
         "Government money market funds hold short-term Treasury and agency paper and are considered very low risk, though they're not FDIC-insured like bank deposits. Prime funds take slightly more credit risk. For most households the practical differences are small; yield and access matter more."),
        ("Should I pay off debt or hold cash?",
         "High-interest debt almost always wins over holding cash earning less. For low-rate debt like a mortgage, the answer depends on the rate, your tax situation, and how much liquidity makes you feel secure - run the numbers, then respect the emotional side too."),
        ("How do laddered CDs or Treasuries work?",
         "You split cash across maturities - say 3, 6, 9, and 12 months - so a portion comes due regularly while the rest keeps earning. Ladders smooth out rate changes and match cash to known spending dates without locking everything up long-term."),
    ],
    # ---------------- professions ----------------
    "business-owner": [
        ("What kind of financial advisor does a business owner need?",
         "One who works at the intersection of the business and the household: entity compensation strategy, retirement plans for owners, concentration and key-person risk, and exit planning. An advisor who only manages investments solves the smallest part of the problem."),
        ("How do I build wealth outside my business?",
         "Systematically, not occasionally: a set owner salary or draw, automatic transfers to investment accounts, maxed tax-advantaged plans, and a target split between reinvesting in the business and diversifying out of it. The goal is a household balance sheet that survives the business having a bad year."),
        ("When should I start planning my exit?",
         "Years before you want out. Exit readiness - clean books, transferable operations, documented processes, a realistic valuation - is what determines whether you sell on your terms. Advisors who work with owners start this conversation early precisely because it takes time."),
        ("Do I need a buy-sell agreement if I have partners?",
         "Yes, and funded. The agreement decides what happens to a partner's share on death, disability, or departure; the funding (usually life and disability insurance) decides whether the surviving owners can actually pay for it. Review it whenever the valuation changes materially."),
        ("How should I think about retirement when the business IS my retirement plan?",
         "Treat that as a hypothesis to test, not a plan. Businesses sell for less than owners expect, at worse times, more often than the reverse. Building liquid investments alongside the business means a disappointing multiple changes your timing, not your retirement."),
    ],
    "executive-professional": [
        ("What financial issues are specific to executives and senior professionals?",
         "Equity compensation (RSUs, options, ESPPs), deferred comp elections, concentrated employer stock, blackout windows, and benefits that change with each promotion or job change. These interact with each other and with taxes in ways generic advice routinely misses."),
        ("How should I handle RSUs when they vest?",
         "Vested RSUs are taxed as ordinary income at vest, and default withholding often under-covers high earners. The planning questions: sell at vest or hold, how much employer concentration you already carry, and how vesting interacts with your bracket this year."),
        ("What should I do with stock options before leaving a job?",
         "Know your post-termination exercise window (often 90 days for ISOs, set by your plan documents), the cost to exercise, and the tax difference between ISO and NSO treatment. Leaving without a decision can forfeit the option value entirely - check your award documents early, not in your final week."),
        ("Is a deferred compensation plan worth using?",
         "It defers income tax and can be powerful in high-earning years, but the money is an unsecured promise from your employer, investments are limited, and payout schedules are rigid. Weigh it against maxing every other tax-advantaged account first and your confidence in the company's solvency."),
        ("How do I coordinate benefits during a job change?",
         "Sequence matters: old 401(k) rollover decisions, new plan enrollment timing, HSA and FSA transitions, option exercise windows, and gaps in life and disability coverage. A short planning session before the start date prevents the common, expensive oversights."),
    ],
    "retired": [
        ("What changes about financial advice once I'm retired?",
         "The goal flips from accumulation to income: sustainable withdrawals, tax-efficient sequencing across accounts, Social Security and pension decisions already locked in, Medicare costs, and protecting against a bad sequence of early returns. Risk management matters more, not less."),
        ("How do I turn my savings into a paycheck?",
         "Common building blocks: a spending floor covered by Social Security, pensions, and possibly annuities; a cash reserve for near-term spending; and a diversified portfolio for everything else. The order you draw accounts - taxable, traditional, Roth - is a tax decision worth real money over a retirement."),
        ("What are required minimum distributions and how do I plan for them?",
         "RMDs force taxable withdrawals from traditional retirement accounts starting at the age set by current law (recently 73, rising for younger cohorts). Planning levers - Roth conversions earlier, qualified charitable distributions, bracket management - work best in the years before RMDs begin."),
        ("Should I claim Social Security at 62, 67, or 70?",
         "Delaying raises the monthly benefit substantially up to age 70, but the right age depends on health, other income, spousal benefits, and whether you're still working. Model the breakevens with your actual numbers; rules of thumb ignore half the equation."),
        ("How do I make sure I don't outlive my money?",
         "Stress-test the plan: lower returns, higher inflation, higher healthcare and long-term care costs, living to 95. A plan that survives those scenarios with margin - and has spending flexibility built in - is what 'enough' actually looks like."),
    ],
    "recently-sold-a-business": [
        ("What should I do first after the sale closes?",
         "Secure the tax reserve before anything else: set aside the estimated federal and state bill in something safe and liquid. Then rebuild the plan the business used to be - income, investments, insurance, estate documents - around the new balance sheet. Most post-sale mistakes come from moving fast, not slow."),
        ("How is my sale taxed and can I still reduce the bill?",
         "It depends on deal structure - stock versus asset sale, installments, earnouts. After closing, remaining levers include timing installment recognition, charitable strategies, and harvesting losses. Anything structural had to happen before the sale; a tax professional can still optimize what remains."),
        ("How do I replace the income my business provided?",
         "From the portfolio now: a sustainable withdrawal rate against the after-tax proceeds, coordinated with any earnout or installment payments, and a cash reserve for the transition years. The number that matters is annual spending versus after-tax assets - build the income plan around it, not around what the business used to pay you."),
        ("Should I invest the proceeds all at once?",
         "Evidence favors prompt investing over long dribbles, but for life-changing liquidity a staged plan over several months is a reasonable emotional compromise. What you should not do is leave the full amount in cash for years waiting for the 'right moment.'"),
        ("Do I need a new estate plan after selling?",
         "Almost certainly yes. The estate built around a business - buy-sell terms, entity structures, old valuations - is now wrong. New documents should reflect liquid wealth, updated exemption planning, and possibly trusts for children, with beneficiaries updated everywhere."),
    ],
    "recently-received-an-inheritance": [
        ("What should I do in the first months after inheriting money?",
         "Confirm what you received, who controls it and which deadlines apply before making large discretionary commitments. Basis, account claims, property obligations and inherited-retirement distributions vary by asset and circumstance; ask the executor or trustee and qualified tax/legal professionals before moving assets."),
        ("How do inherited retirement accounts work?",
         "The inherited-account deadline and withdrawal rules depend on account type, beneficiary status, date of death and whether the owner had begun required distributions. Spouses may have additional choices. Confirm titling, annual requirements and tax treatment with a qualified tax professional using current IRS Publication 590-B."),
        ("What does 'step-up in basis' mean for me?",
         "Certain inherited assets may receive a basis determined by date-of-death value, but the result can vary by asset and circumstances. Obtain the estate's valuation and basis records, then ask a tax professional to calculate the gain or loss before deciding to sell."),
        ("Should I use the inheritance to pay off debt or invest it?",
         "Compare debt interest, required cash reserves, taxes and the risks of investing rather than assuming one answer for every household. Write down an allocation for debt, reserves, investing and giving after confirming what assets are actually available."),
        ("How do I handle an inheritance shared with siblings or held in trust?",
         "Shared assets need explicit agreements about use, sale, or buyout - put it in writing while everyone is still friendly. Trust assets come with a trustee, distribution terms, and tax filings of their own. An advisor plus an estates attorney keeps both from becoming family conflict."),
    ],
    "entrepreneur-founder": [
        ("What financial planning is different for startup founders?",
         "Nearly all wealth is illiquid and concentrated in one private company, income is often below market, and outcomes are binary-ish. Planning centers on personal runway, QSBS eligibility from day one, equity and option strategy at each round, and not letting the company's risk profile become the household's."),
        ("What is QSBS and why do founders care?",
         "Qualified Small Business Stock (Section 1202) can exclude a large amount of federal capital gains on qualifying C-corp shares held for the required period, with rules that changed for stock issued after July 2025. Eligibility decisions are made at incorporation and each issuance - get it confirmed by a tax professional early, because it's nearly impossible to fix later."),
        ("Should I take secondary sales when investors offer them?",
         "Selling a slice at a priced round diversifies your risk without leaving the company, and many advisors encourage it once the position is life-changing on paper. Weigh it against signaling concerns, board dynamics, and taxes on the gain. A partial sale that secures the household changes how you run the company - usually for the better."),
        ("How should I handle my founder equity and options as we raise?",
         "Track vesting, exercise costs, and AMT exposure at each stage; consider early exercise or 83(b) elections where applicable (deadlines are short and absolute); and model dilution per round. Equity decisions at startups have strict deadlines that do not move."),
        ("What personal finance basics matter most before an exit?",
         "Runway (12+ months of expenses accessible), insurance (health, disability, term life), a real salary when the company can pay one, and retirement contributions even in lean years. Founders who skip the basics make company decisions from personal fear - expensive for both."),
    ],
    # ---------------- cities ----------------
    "austin": [
        ("How do I find a good financial advisor in Austin?",
         "Start with fiduciary, fee-transparent advisors who work with situations like yours - Austin's mix of tech equity, business owners, and relocations means relevant experience varies a lot. Verify registration on the SEC's Investment Adviser Public Disclosure site, interview two or three, and compare full fee quotes in dollars."),
        ("What does a financial advisor in Austin typically cost?",
         "Common models: a percentage of assets managed, flat annual planning fees, or hourly. Ask each advisor for their total cost at your asset level in dollars per year. Prices in Austin track national norms more than local ones - what varies is the service behind the fee."),
        ("Do Austin advisors work with tech employees and equity compensation?",
         "Many do - it's one of the city's defining client profiles. Ask specifically about RSU strategy, option exercise planning, ESPP, and concentrated employer stock, and whether they've worked with employees of your company or similar ones."),
        ("Does Texas having no state income tax change the advice I need?",
         "It shifts planning emphasis: no state tax means Roth conversions and capital gains decisions are federal-only calculations, and property taxes and federal deduction caps matter more. If you relocated from a high-tax state, timing income across the move year is a real planning item."),
        ("Can I work with an advisor who isn't based in Austin?",
         "Yes - most advisory relationships work fine remotely, and some people prefer a specialist over a local generalist. Local knowledge matters most for Texas-specific items like property tax and homestead rules, which any Texas-savvy advisor handles."),
    ],
    "los-angeles": [
        ("How do I find a good financial advisor in Los Angeles?",
         "Define what you need first - LA's advisory market spans entertainment, tech, real estate, and business ownership, and relevant experience differs widely. Verify registration on the SEC's Investment Adviser Public Disclosure site, ask for fiduciary status in writing, and interview two or three before deciding."),
        ("What does a financial advisor in Los Angeles typically cost?",
         "Expect the standard national models: a percentage of assets, flat annual fees, or hourly rates, with LA's large advisor market offering every tier. Compare the all-in dollar cost per year at your asset level, including underlying fund fees."),
        ("How do California taxes affect financial planning in LA?",
         "California's top income tax rate is the nation's highest and capital gains are taxed as ordinary income - so Roth conversion timing, equity compensation decisions, asset location, and residency planning carry more weight here than in most states. Any multi-state move deserves planning before the moving truck."),
        ("Do LA advisors work with entertainment industry finances?",
         "A real specialty exists for it: irregular income, residuals, loan-out corporations, and union pensions. If that's your world, ask for direct experience with entertainment clients - the structures are specific enough that generalist advice often misses them."),
        ("Can I work with an advisor outside California?",
         "Yes, and many people do. Just confirm they understand California tax and estate rules as they apply to you - community property, state capital gains treatment, and Proposition 19 property rules are the items out-of-state advisors most often get wrong."),
    ],
    "chicago": [
        ("How do I find a good financial advisor in Chicago?",
         "Start with fiduciary advisors experienced in your situation - Chicago's mix of corporate executives, business owners, and traders means specialization matters. Verify registration on the SEC's Investment Adviser Public Disclosure site, ask for fee quotes in dollars, and interview two or three."),
        ("What does a financial advisor in Chicago typically cost?",
         "The usual national models apply: percentage of assets, flat annual planning fees, or hourly rates. Chicago's deep advisor market means competitive pricing at every tier - compare the total dollar cost and what's included, not just the headline rate."),
        ("How do Illinois taxes affect my financial plan?",
         "Illinois has a flat state income tax, but notably exempts retirement income - Social Security, pensions, and retirement account withdrawals - from state tax. That changes Roth conversion math and withdrawal sequencing for retirees compared to most states. Property taxes, among the highest nationally, are the other planning constant."),
        ("Are there advisors who specialize in trading and derivatives income?",
         "Yes - Chicago's exchanges support a real specialty in trader tax status, futures and options taxation, and entity structuring for trading income. If that's you, ask for direct experience; the tax treatment differs enough from wages that generalists routinely get it wrong."),
        ("Can I work with an advisor who isn't local?",
         "Yes. Remote relationships are standard now. What you want local or state knowledge for: Illinois retirement-income tax treatment, property tax appeals and exemptions, and any Illinois estate considerations."),
    ],
    "new-york": [
        ("How do I find a good financial advisor in New York?",
         "Define the job first - NYC's market ranges from Wall Street comp specialists to business-owner planners. Verify registration on the SEC's Investment Adviser Public Disclosure site, get fiduciary status in writing, and compare two or three full fee quotes in dollars before deciding."),
        ("What does a financial advisor in New York typically cost?",
         "All standard models exist - percentage of assets, flat fees, hourly - with NYC offering every tier from national firms to boutiques. Fees here run the full range; compare total annual dollars at your asset level and the service behind them."),
        ("How do New York taxes change financial planning?",
         "New York State plus NYC income tax combine to one of the highest burdens in the country, so bracket management, bonus and equity timing, deferred comp, and residency planning matter more than almost anywhere else. Moving to or from the city is itself a major planning event."),
        ("Do NYC advisors specialize in finance-industry compensation?",
         "Yes - deferred comp, carried interest, restricted stock, year-end bonus timing, and compliance-driven trading restrictions are a mature specialty here. If that's your compensation, ask for direct experience with your employer type; the rules differ enough by firm to matter."),
        ("Can I work with an advisor outside New York?",
         "Yes - remote advice is standard. Keep state and city tax knowledge non-negotiable: NY residency audits are aggressive, and getting the move-year or remote-work allocation wrong is expensive."),
    ],
    # ---------------- combos ----------------
    "austin-retirement-planning": [
        ("How do I find a retirement planning advisor in Austin?",
         "Look for fiduciary advisors whose core work is retirement transitions - withdrawal strategy, Social Security timing, Roth conversions - not just investment management. Verify registration on the SEC's Investment Adviser Public Disclosure site and interview two or three with your actual numbers."),
        ("Does Texas being tax-free change retirement planning?",
         "Yes, helpfully: Texas taxes no retirement income, so withdrawal sequencing and Roth conversion decisions are federal-only math. Retirees relocating from high-tax states should plan the move-year carefully - income recognized before versus after establishing Texas residency is taxed very differently."),
        ("When should an Austin retiree start Roth conversions?",
         "The window between retirement and required minimum distributions is usually the sweet spot: lower income years let you convert at lower federal brackets with no state tax layer at all. The right amount each year depends on your bracket, IRMAA exposure, and other income."),
        ("What does retirement planning cost in Austin?",
         "Flat-fee retirement plans, percentage-of-assets relationships, and hourly engagements all exist locally. For a one-time plan, expect a flat project fee; ongoing management is usually asset-based. Get the total in dollars and what's included before comparing."),
        ("Can I do retirement planning with an advisor who isn't in Austin?",
         "Yes - the work is numbers, not geography. What matters is fluency in Texas's tax picture (simple) and the federal retirement rules (identical everywhere). Choose on expertise and fee, not ZIP code."),
    ],
    "los-angeles-retirement-planning": [
        ("How do I find a retirement planning advisor in Los Angeles?",
         "Seek fiduciary advisors whose daily work is retirement transitions - withdrawal sequencing, Social Security, Roth strategy - and who actively plan around California taxes. Verify registration on the SEC's Investment Adviser Public Disclosure site and interview two or three with your real numbers."),
        ("How do California taxes affect retirement planning?",
         "California taxes most retirement income, including IRA and 401(k) withdrawals and capital gains as ordinary income - though not Social Security benefits. That materially changes Roth conversion math, withdrawal sequencing, and the value of relocating in retirement. Plan conversions with the state layer included."),
        ("Is retiring in California worth it financially?",
         "For many people the decision isn't purely financial - but know the numbers: high income tax on withdrawals, high property costs, partial offsets like Proposition 19's property tax portability for those 55+. An advisor can model staying versus relocating against your actual plan before you decide."),
        ("What does retirement planning cost in Los Angeles?",
         "Flat project fees for a one-time plan, asset-based fees for ongoing management, and hourly options all exist in LA's deep market. Compare total annual dollars at your asset level and confirm tax planning is included, not just investments."),
        ("Can I work with a retirement advisor outside California?",
         "Yes, with one caveat: California tax fluency is non-negotiable. An out-of-state advisor must understand CA's treatment of retirement income, capital gains, and residency rules - those are where mistakes get expensive."),
    ],
}
