"""Six specialty guides for editorial review."""
SPECIALTY_GUIDES = {
'retirement-planning': '''
<h2>Begin with the retirement you need to fund</h2>
<p>Retirement planning is not one target balance. It is a sequence of decisions about when income stops, what spending remains, which income sources start when, and how much uncertainty the plan can bear. Separate essential spending from flexible spending and one-time costs. Add housing, health care, family support and taxes. An advisor should show a year-by-year cash-flow view and explain what changes when one spouse retires before the other or lives much longer. A single calculator output can start a conversation, but it cannot replace that work.</p>
<h2>Know which income is dependable and which is variable</h2>
<p>List Social Security, pensions, annuities, part-time work and portfolio withdrawals separately. Social Security claiming affects the monthly benefit and can affect survivor income; get current estimates from <a href="https://www.ssa.gov/retirement/plan-for-retirement">SSA's retirement planner</a>. A pension may offer a lump sum, lifetime payments or survivor options. Compare these using actual plan terms, inflation exposure, tax treatment and the needs of both spouses before making an irreversible election. The investment portfolio then has a clearer job: cover gaps, absorb surprises and preserve longer-term purchasing power.</p>
<p>Ask an advisor to illustrate low-return and high-inflation periods, not only an average market. Losses early in retirement while withdrawing can shrink the capital available for recovery. A cash or short-term bond reserve may help meet immediate spending, but a reserve that is too large may lose purchasing power. The right balance depends on guaranteed income, flexibility and risk tolerance.</p>
<h2>Coordinate taxes across account types</h2>
<p>Withdrawals from taxable, traditional tax-deferred and Roth accounts have different effects. A Roth conversion can increase current tax and sometimes Medicare-related costs while reducing future traditional-account balances. Required minimum distributions depend on the account and birth year; check the <a href="https://www.irs.gov/retirement-plans/retirement-plan-and-ira-required-minimum-distributions-faqs">IRS's current RMD guidance</a>. Ask who prepares annual tax projections, who works with your CPA, and how the plan changes after a spouse dies. Do not choose a conversion or withdrawal order from a generic article.</p>
<h2>Stress-test health and longevity</h2>
<p>Compare current insurance and Medicare costs from <a href="https://www.medicare.gov/basics/costs/medicare-costs">Medicare's current cost page</a>. Ask what the plan assumes for premiums, out-of-pocket care, long-term care, housing changes and help for relatives. A plan that works only if both people die at average life expectancy is not a resilient plan. An advisor should show what can be adjusted if costs rise, and coordinate estate-document questions with an attorney rather than drafting them.</p>
<h2>Watch for decisions that cannot easily be undone</h2>
<p>A pension election, annuity purchase and Social Security claim can affect income for decades. Before selecting a lump sum, ask whether the plan provides a survivor benefit, whether payments adjust for inflation, and what happens if the employer plan or insurer fails. Compare offers in the same after-tax dollars and assumptions. A rollover may preserve control but transfers investment and longevity risk to your household. Ask for a side-by-side decision sheet, not a one-number recommendation.</p>
<p>Retirement timing can also determine health coverage. A person leaving work before Medicare eligibility may need a bridge, while someone enrolling in Medicare must understand enrollment windows and how other coverage interacts. Verify current costs and enrollment rules with Medicare and a benefits specialist rather than a static projection. If one spouse is younger, run separate dates for each person's coverage.</p>
<h2>Demand an action plan, not just a Monte Carlo score</h2>
<p>Ask for a baseline annual spending and withdrawal table, plus at least a bad-early-market case, higher health costs and a longer lifespan. The output should say what you would do: delay a large purchase, change withdrawals, rebalance, or revisit work. Specify which spending is discretionary and which is not. Update the model when actual market returns or household facts depart from assumptions; a high probability generated today is not a warranty for tomorrow.</p>
<h2>Understand the fee and scope</h2>
<p>Some planners charge hourly or a flat project fee; others bill ongoing asset-based fees or receive insurance compensation. The right arrangement depends on whether you want a one-time second opinion, an annual tax-aware withdrawal plan or delegated investment management. Ask for the first-year and ongoing cost in dollars, what investment fund charges add, and whether the planner will work with accounts they do not manage. A recommendation for an annuity or rollover deserves a clear comparison against keeping current benefits and accounts.</p>
<p>Ask how often the plan is revised, who meets with a surviving spouse, and whether you will receive a written action list after each review. "Financial planning" on a proposal is not the same as a deliverable. The advisor should spell out when the Social Security choice is revisited, when actual spending is reconciled, and who coordinates with tax and estate professionals.</p>
<h2>Use the first meeting to test the service</h2>
<ol><li>Can I see a sample annual withdrawal plan with account types, taxes and spending flexibility?</li><li>How do you model Social Security and pension choices for both spouses?</li><li>What action changes after a prolonged bear market or a health shock?</li><li>Who updates the model, how often and at what total annual cost in dollars?</li><li>How do you coordinate tax and estate issues with licensed specialists?</li></ol>
<p>Check registration, fees, conflicts and disclosures through <a href="https://www.investor.gov/introduction-investing/getting-started/working-investment-professional/using-iapd">Investor.gov's IAPD guide</a>. Unlike most directory topics here, a retirement-tagged advisor appears in this roster; a tag is not a guarantee of fit, service or outcome. Compare the work and fee, and use the related retirement calculators for illustrations.</p>
''',
'managing-investments': '''
<h2>Decide what the portfolio is for</h2>
<p>Investment management begins with goals, withdrawal horizon and the risks your household can bear. Money needed next year has a different job from money funding retirement decades away. Map accounts and restrictions together, including workplace plans, taxable accounts, employer stock and cash reserves. An advisor's proposal should explain target allocation, how much loss to expect in adverse markets, how and when holdings are rebalanced, and what would cause a change. Avoid promises of a market-beating return or a risk-free high yield.</p>
<h2>Look through the holdings</h2>
<p>Owning several funds does not necessarily mean you are diversified: they may hold many of the same stocks. Ask for an account-level view of stocks, bonds, cash, sectors and countries, including employer shares. Check what is inside a fund, the liquidity of each investment and any concentration in one industry. Investor.gov explains <a href="https://www.investor.gov/introduction-investing/getting-started/asset-allocation">asset allocation and diversification</a>, and why rebalancing returns a portfolio to its intended risk profile rather than predicting market winners.</p>
<p>Taxable and retirement accounts can hold different assets for tax reasons, but tax treatment is not the only concern. Ask how the advisor decides where to hold assets, whether proposed turnover creates taxes, how tax-loss harvesting is applied and when wash-sale rules could interfere. A CPA should check individualized tax effects. If a portfolio contains annuities, private funds or other complex products, ask for separate liquidity and compensation details.</p>
<h2>Place investments within the rest of life</h2>
<p>An investment policy should account for mortgage payments, job risk, insurance, taxes, future tuition and any private business exposure. An advisor who only sees assets transferred to their platform may underestimate a large employer-stock position elsewhere. Ask them to include outside accounts in the risk view even if they cannot trade them. A portfolio may be diversified inside itself while the household remains concentrated in a business, property or career.</p>
<p>When reviewing a proposal, distinguish expected return from a guaranteed outcome. Ask to see a downside range, planned withdrawals and an inflation assumption. If income is needed soon, define how much comes from cash, bonds and equities and what happens after a bad year. If no income is needed for decades, ask why the allocation still fits your ability to stay invested through losses.</p>
<h2>Separate process from predictions</h2>
<p>Market timing stories and last year's top fund are easy to sell; a repeatable process is more useful. Ask how target weights are set, what triggers rebalancing, what tax limits apply, and when the process overrides its own model. If active management is proposed, ask how success will be assessed after fees and taxes over a suitable period. If passive funds are proposed, ask how they fit the need for cash, bonds or inflation exposure. Neither label removes the need for household-level planning.</p>
<h2>Set a decision policy for bad markets</h2>
<p>A useful investment policy says what the portfolio funds, what allocation range you will tolerate, when to rebalance, and what cash is available for near-term spending. It should also name who can authorize changes and how you will react after a sharp decline. If you need income, ask how withdrawals will be funded when markets are down. If a salesperson presents a model with only historical winning periods, ask for the assumptions and downside cases.</p>
<h2>Understand discretion, custody and reporting</h2>
<p>Ask whether the advisor will have discretion to trade without seeking permission each time, which firm holds the assets, and how you can independently review statements. The custodian is not the same as the advisor. Determine whether performance reports include all fees, cash flows and taxes, and compare results with an appropriate benchmark and your own goal rather than whichever index had a good quarter. A strategy that cannot explain its risk and cost in plain language is hard to evaluate.</p>
<p>Review what happens if you leave the firm. Can holdings transfer in kind or must they be sold? Are any products proprietary, illiquid or subject to surrender charges? What happens to a taxable account if positions with large gains are liquidated for a new model? The first transition can be as consequential as the ongoing asset allocation, so ask for a transition plan before signing authority.</p>
<h2>See the full cost, not a percentage alone</h2>
<p>An assets-under-management fee, fund expense ratios, transaction charges and product commissions can stack. Ask for the total expected annual cost in dollars at your balance, plus one-time costs and what happens if the account grows. What financial planning is included? Can you get advice without handing over the portfolio? Compare that service with lower-cost alternatives suited to your needs. <a href="https://www.investor.gov/introduction-investing/getting-started/understanding-fees">Investor.gov's fee guide</a> explains why even recurring costs that look small can matter over time.</p>
<h2>Questions for an advisor</h2>
<ol><li>How do you set an allocation from my goals and existing holdings?</li><li>What does the portfolio own beneath fund labels, and what is concentrated?</li><li>How do you manage taxes without promising a particular tax outcome?</li><li>What is my total annual cost in dollars, including funds and other compensation?</li><li>Who makes trades, holds custody and reports performance against the agreed goal?</li></ol>
<p>Verify the professional and read firm disclosures with <a href="https://www.investor.gov/introduction-investing/getting-started/working-investment-professional/check-out-your-investment-professional">Investor.gov</a>. No investment-management specialist is currently tagged on this page; the profiles below are a general roster, not a verified specialist match. Ask each advisor what they actually do and charge. The related investing calculators help you explore assumptions, not predict returns.</p>
''',
'business-owner-wealth-planning': '''
<h2>Treat the business as part of the household's balance sheet</h2>
<p>A profitable business can still leave its owner cash-poor. Business value, operating cash, owner pay, personal investments and debt guarantees interact. A planning conversation should distinguish the company's cash needs from the household's reserves and long-term assets. Ask the advisor to model a weak quarter, a partner departure and a sale that takes longer or nets less than expected. A valuation is neither guaranteed proceeds nor retirement savings.</p>
<h2>Choose the question before choosing the advisor</h2>
<p>Owners at different stages need different help. Early on, the priority may be stable compensation and estimated tax payments. With employees, a retirement plan introduces eligibility, administration and employer-cost questions. As the owner approaches an exit, after-tax proceeds, business succession and concentrated wealth dominate. One professional does not replace a CPA, business lawyer and transaction specialist. Ask who will coordinate and who owns each deliverable.</p>
<p>The <a href="https://www.irs.gov/retirement-plans/retirement-plans-for-self-employed-people">IRS self-employed retirement-plan guide</a> outlines plan types; a one-participant 401(k) is subject to staffing and eligibility rules. Plan contributions and estimated tax payments vary by entity and year. Build the cash calendar with the CPA rather than assuming one universal owner formula. See <a href="https://www.irs.gov/businesses/small-businesses-self-employed/estimated-taxes">IRS estimated-tax guidance</a>.</p>
<h2>Build wealth outside the company deliberately</h2>
<p>Reinvestment can be sensible, but putting every excess dollar into the company concentrates career, income and wealth in one asset. Define operating reserve needs and a household reserve, then an explicit transfer policy into diversified long-term savings when cash flow allows. Insurance and partner agreements address some downside risk; only counsel should draft the agreements. Ask an advisor to show whether the personal plan survives a year of lower distributions and whether an exit is required to meet retirement goals.</p>
<h2>Track guarantees and protection gaps</h2>
<p>Personal guarantees on business borrowing can make company debt a household obligation in a downturn. Insurance and entity structures may mitigate some risk, but neither is a universal shield. Ask counsel and insurance specialists to review actual policies and contracts, while the advisor models the household cash needed if revenue or an owner stops working. A buy-sell agreement with partners should be reviewed for funding and valuation assumptions; a beautifully drafted agreement without money to execute it can fail at the moment it matters.</p>
<p>Separate key-person risk from the owner's own disability or death: who runs operations, who signs on debt, and how long can payroll continue? This is the bridge between business succession and personal planning. The answer changes what belongs in liquid reserves, insurance and the timing of an exit plan.</p>
<h2>Model the cost of not selling</h2>
<p>An exit is an option, not a certainty. Test an owner continuing to operate, handing over management, transferring to family, selling only a share, or closing a weaker business. Each affects income, insurance, personal guarantees and retirement timing. A useful plan funds household goals under at least one scenario that does not require a perfect buyer at a perfect price. If the company is part of a marital or family balance sheet, ask how the plan changes for illness, disability or a partner dispute.</p>
<p>Owner compensation should be deliberate: recurring personal pay supports household budgeting, while distributions and business reinvestment depend on entity structure, cash flow and taxes. The CPA must set compliant compensation and estimated payments. An advisor can help decide how much liquid wealth should be built away from the operating company so personal finances are not hostage to one asset.</p>
<h2>Plan for several exit outcomes</h2>
<p>Model cash at close, debt repayment, deal costs, taxes, escrow, contingent earnouts and any retained equity separately. The <a href="https://www.irs.gov/businesses/small-businesses-self-employed/sale-of-a-business">IRS business-sale overview</a> explains why tax treatment varies across the assets sold. A transaction CPA and lawyer should analyze the actual deal, before documents are signed. The advisor's job is to translate net, available proceeds into spending, investing and risk decisions without claiming a particular valuation or tax benefit.</p>
<h2>Make a shared calendar with the CPA and attorney</h2>
<p>Tax estimates, benefit elections, insurance renewals, partner-agreement reviews, banking covenants and potential sale milestones rarely happen on one schedule. Put them together. Ask who prepares each number, who confirms it and what can wait. An advisor may coordinate the household view but should not claim to sign off on tax treatment or legal terms. If several professionals disagree, the owner needs a documented decision and responsible person rather than three separate memos.</p>
<h2>Interview questions and costs</h2>
<ol><li>What comparable owner situations have you handled, and which work products can you show without exposing client data?</li><li>How do you model business concentration and the household's liquid reserve?</li><li>What decisions belong to you versus the CPA, lawyer or plan administrator?</li><li>How do you price planning before and after a liquidity event?</li><li>How will you report the total annual cost in dollars, including managed-fund costs?</li></ol>
<p>Read the firm's Form ADV and verify registration and conflicts using <a href="https://www.investor.gov/introduction-investing/getting-started/working-investment-professional/using-iapd">IAPD</a>. Valora has no business-owner wealth specialist tagged on this page; the profiles below are a general roster. Ask them directly about your situation. The <a href="/financial-advisor-for-business-owners/">business-owner guide</a> and related investing tools go deeper on the planning sequence.</p>
''',
'selling-a-business': '''
<h2>Start before a buyer sets the clock</h2>
<p>Selling a company can change the household's wealth in one transaction, but preparation starts years earlier. Document recurring revenue, owner dependence, customer concentration, contracts, debt and personal guarantees. Get a realistic range of valuations and consider what the business could be worth without you running every relationship. A financial advisor can model what different proceeds mean for your life; a business broker or banker handles the sale process, a transaction lawyer protects the deal terms, and a CPA assesses tax structure. Ask each professional what they own before one deadline forces rushed choices.</p>
<h2>Test the buyer and the deal terms, not only the valuation</h2>
<p>Two offers with the same headline price can have very different value. Compare cash versus contingent amounts, escrow size, buyer financing, working-capital adjustments, employment obligations and retained shares. Ask the transaction team how a deal can fail between letter of intent and closing. The advisor's personal planning model should not spend an earnout before it is earned. If retained equity is offered, consider the buyer's capital structure and your ability to sell later; the transaction lawyer should explain the documents.</p>
<h2>Separate deal price from spendable proceeds</h2>
<p>Model cash at closing, transaction fees, debt payoff, working-capital adjustments, taxes, escrow, contingent earnouts and retained equity as distinct lines. An earnout is not cash in your account and rollover equity may still be concentrated and illiquid. Ask for downside scenarios where the transaction falls through or contingent payments never arrive. The <a href="https://www.irs.gov/businesses/small-businesses-self-employed/sale-of-a-business">IRS overview of a business sale</a> explains why inventory, depreciable property and capital assets can have different tax treatment. Do not assume the entire sale price is a capital gain.</p>
<h2>Discuss tax structure before the definitive agreement</h2>
<p>Asset and stock sales may affect buyer and seller differently; allocation of a purchase price among assets can carry reporting consequences. For certain transactions the IRS uses <a href="https://www.irs.gov/forms-pubs/about-form-8594">Form 8594</a>. An installment payment schedule can alter timing, but the <a href="https://www.irs.gov/publications/p537">IRS installment-sale rules</a> are not a substitute for reviewing your contract. Potential qualified small business stock treatment, charitable planning and estate structures depend on specific facts and often require action before signing. A transaction CPA and lawyer should verify eligibility, not a directory article or advisor's verbal assurance.</p>
<h2>Watch the timeline of commitments</h2>
<p>Before a letter of intent, many options remain open. Once exclusivity, financing, earnout metrics and indemnities are negotiated, the practical room to change terms narrows. Ask for a decision calendar showing which choices are truly time-sensitive and who advises on each. A buyer may push for speed; the household should understand whether tax, estate and personal liquidity scenarios have been updated to the current draft of the agreement, not an earlier offer.</p>
<p>At closing, preserve a clean record of basis, asset allocations, fees and proceeds for the CPA, and track future obligations and contingent payments. Treat the transition as a sequence, not an event: taxes may be due before an earnout arrives, and a legal dispute can delay escrow. A planner's role continues after the sale only if the scope and ongoing cost are clear in writing.</p>
<h2>Write a post-close plan before closing</h2>
<p>Decide what amount must stay liquid for taxes and transition costs, what annual spending will replace owner pay, and what share of proceeds can be invested for long-term goals. Revisit insurance, an estate plan built for a business, and the household's risk appetite after a sudden change in wealth. A written investment policy can keep a new lump sum from turning into ad hoc commitments. The advisor should not pressure you to transfer the whole amount on the day the wire arrives; ask what the first 30, 90 and 365 days of work would deliver.</p>
<h2>Prepare the household for an identity and income change</h2>
<p>A business can supply community, routine and status as well as money. Decide what you will do with time and how much spending you want after sale. If your spouse, children or partners worked in the company, the change can affect several incomes at once. Ask the advisor to model core living costs, discretionary goals, support for family and philanthropic choices separately. A pause after closing need not mean no plan; it means a written sequence for cash reserves, taxes, decisions that can wait and decisions that cannot.</p>
<p>Review beneficiary designations, wills, trusts, insurance and investment policy after the balance sheet changes. Do not assume existing business-oriented documents automatically fit a liquid portfolio. The estate attorney should lead document changes; the advisor should track how funds and titles actually move.</p>
<h2>Compare the service and price</h2>
<ol><li>What have you done for an owner at my stage, and can you show a redacted sample proceeds model?</li><li>Who leads tax, legal, valuation and personal planning decisions?</li><li>How do you stress-test earnout failure and a delayed sale?</li><li>What do you charge before the deal and after it, in dollars? Is planning available without handing over assets?</li><li>Will you document the assumptions and update them if terms change?</li></ol>
<p>Verify the adviser and firm disclosures using <a href="https://www.investor.gov/introduction-investing/getting-started/working-investment-professional/using-iapd">Investor.gov's IAPD guide</a>. No selling-a-business specialist is tagged on this page. The profiles below are a general roster; ask each advisor about location, transaction experience and fit. The related investing calculators can illustrate assumptions but cannot price a deal.</p>
''',
'cash-liquidity-management': '''
<h2>Cash needs more than one label</h2>
<p>"Cash" may mean next month's bills, an emergency reserve, a tax payment in six months, a home down payment in two years or proceeds that will eventually be invested. Give each amount a purpose and deadline. That tells you which balances need immediate access and which can tolerate a term or modest market risk. A cash-management advisor should ask about household spending, variable income, known payments and the source of any windfall before suggesting a product.</p>
<h2>Plan for a shock, not a slogan</h2>
<p>Three to six months of spending is a common starting rule, not a universal prescription. Someone with stable dual incomes, little debt and good insurance may need less than a household whose income is tied to one business. A reserve should cover realistic essential costs and be accessible when the primary income source fails. Add known near-term spending separately so a planned tax bill does not consume the emergency fund. If cash is temporarily high after an exit or inheritance, document how much is owed for taxes before allocating the rest.</p>
<h2>Check protections at the account level</h2>
<p>FDIC insurance is applied by insured bank, ownership category and depositor, not simply by website logo or app. A deposit platform may spread funds across program banks, but confirm which banks actually hold balances and what else you hold at them. A money market fund, even one investing in government securities, does not receive bank deposit insurance. Broker failure protection and protection against a decline in a fund's value are different questions. An advisor should be able to show the product name, underlying institution and exact access terms.</p>
<h2>Make the money available when it is due</h2>
<p>A ladder can split a known tax bill or home purchase across maturities, but rates change and early sale may produce a different value. For unpredictable emergencies, immediate access matters more. Ask how fast money moves from a savings account, bill or fund to the account that pays the expense, and whether transfer limits, settlement or weekends matter. Test the operational path before an urgent payment; a high yield that cannot arrive in time fails the job.</p>
<p>Cash planning should be revisited after a job change, business sale, inheritance, property purchase or large tax event. A one-time rule of thumb cannot keep pace with changing obligations. Document who reviews balances and how often, especially if several accounts or family members are involved.</p>
<h2>Choose a home for each time horizon</h2>
<p>Checking and savings accounts, Treasury bills, CDs and money market funds differ in access, yield, guarantees and operational risk. A bank deposit may have federal deposit insurance subject to ownership category and institution limits; a money market mutual fund is an investment and is not FDIC-insured. Do not confuse a bank's "money market account" with a mutual fund. Check current coverage through the <a href="https://www.fdic.gov/resources/deposit-insurance/understanding-deposit-insurance">FDIC's deposit-insurance guide</a> and confirm the exact institutions and ownership categories before placing a large sum.</p>
<p>Treasury bills have maturity dates and can be sold earlier, potentially at a different price. CDs may impose early-withdrawal penalties. Funds can have expense ratios and settlement delays. Compare after-tax yield, safety and access, not headline rates alone. If cash is at a brokerage, ask what is in the sweep and what coverage actually applies; SIPC protection for brokerage failure is not protection from market losses.</p>
<h2>Compare advice with simple alternatives</h2>
<p>Cash management can be straightforward. A high-yield insured savings account or short Treasury bill may meet a short-term need without an ongoing percentage-of-assets fee. Complex sweep programs, ladders and funds can be appropriate in some cases, but ask what additional service they deliver after costs and access constraints. If the advisor will charge on balances held in cash, get the fee in dollars and ask whether it is justified by the work performed.</p>
<p>For a business owner, cash in an operating account has a different purpose from a household emergency reserve; for a retiree, a spending buffer has a different purpose from a tax reserve. Document those distinctions so yield comparisons do not accidentally move money away from its job. Review interest and insurance terms when bank relationships or account ownership change.</p>
<h2>Know the tradeoff with debt and investing</h2>
<p>Cash held long term can lose purchasing power to inflation, while investing near-term obligations in volatile assets risks a forced sale. High-interest debt may cost more than cash earns, but a payoff should not eliminate the reserve needed to avoid borrowing again. Ask an advisor to compare after-tax interest, liquidity, debt terms and the household's comfort with uncertainty. A ladder of maturities can align money with dates, but only if those dates and penalty terms are understood.</p>
<h2>Questions for the advisor</h2>
<ol><li>How will you map balances to deadlines and access needs?</li><li>Which accounts are deposits, and which are investments?</li><li>What insurance or protection applies to my exact account structure?</li><li>What is the after-fee, after-tax yield and cost of early access?</li><li>How are you paid, and do you receive compensation for moving cash into a particular product?</li></ol>
<p>Read the firm's disclosures and check registration using <a href="https://www.investor.gov/introduction-investing/getting-started/working-investment-professional/using-iapd">Investor.gov</a>. No liquidity specialist is tagged here; the profiles below are a general roster, so ask about location and fit. The related banking calculators help compare scenarios, not guarantee yields or protection.</p>
''',
'concentrated-stock': '''
<h2>Measure the whole exposure to one company</h2>
<p>A concentrated position is more than the shares visible in a brokerage account. Include RSUs not yet vested, stock options, employer shares in a retirement plan, a spouse's employer exposure and any salary or bonus tied to the same firm. Calculate the share of liquid investments and total household wealth connected to that company, then ask what happens if its value falls sharply at the same time a job is lost. Investor.gov explains <a href="https://www.investor.gov/introduction-investing/getting-started/asset-allocation">diversification and asset allocation</a>.</p>
<h2>Understand why the position cannot simply be sold today</h2>
<p>Some shares are restricted, subject to blackout periods or held through an employee plan. An insider may need a compliant trading plan or legal clearance. A private-company stake may have transfer restrictions and no market at all. Other holdings have low tax basis, large unrealized gains or charitable plans. An advisor should distinguish real restrictions from a preference not to sell and coordinate with company counsel and a CPA before proposing a transaction.</p>
<h2>Respect trading rules and implementation limits</h2>
<p>Employees and executives may face blackout windows or possession of material nonpublic information. A Rule 10b5-1 trading plan is a legal and compliance tool with conditions, not an automatic permission slip. Company counsel and compliance should approve the process before any schedule is put in motion. Options, hedges or borrowing against shares can add costs and new risks, and may be forbidden by company policy. Ask an advisor to specify what is feasible for your particular share class and role.</p>
<p>After a reduction, decide where the proceeds go before trading. A diversified mix, cash for near-term needs and debt repayment can all be candidates; their balance follows the household plan. Otherwise a sale may simply move concentration from one fashionable asset to another.</p>
<h2>Compare several ways to reduce risk</h2>
<p>Gradual sales, sales at vest, a target concentration limit, charitable giving of appreciated shares or hedging instruments may be considered depending on eligibility, taxes, restrictions and cost. None is a universal answer. A donor-advised fund or trust has legal and tax consequences. Borrowing against concentrated shares adds margin or collateral-call risk rather than removing concentration. Ask for a written scenario comparison that shows after-tax proceeds, remaining exposure, costs and what changes if the stock falls before the plan is complete.</p>
<h2>Do not let tax avoidance become the entire strategy</h2>
<p>Deferring a tax bill can be valuable, but it has a cost if a large stock position remains exposed to one company's performance. Ask for an after-tax comparison of a staged sale, a faster reduction and a continued hold under both rising and falling prices. The analysis should show the dollars still at risk, not only the percentage of gains that would be taxed. A low basis is a fact, not a plan by itself; a future estate result also depends on law and personal circumstances.</p>
<h2>Build a process that survives a changing price</h2>
<p>A plan made while the stock is rising can be abandoned after a fall, and one made in panic after a fall can lock in a loss unnecessarily. Establish review dates, target ranges and authorization rules in advance. Ask whether the plan uses a fixed-dollar sale, a percentage reduction, a target maximum position or scheduled diversification at vest. Then test each approach under up, flat and down prices and after tax. The goal is a decision you can explain and follow, not a prediction of the next peak.</p>
<p>Some positions have sentimental meaning or are tied to a founder's identity. A good advisor acknowledges that while still showing what a worst-case outcome would do to retirement, education or family support. A deliberate amount to keep can be part of a plan, but label it as risk you choose to retain.</p>
<h2>Keep a decision calendar</h2>
<p>List vest dates, option expiration, permitted trading windows, tax-payment dates and planned review points. Discuss what must be decided before a job change or liquidity event. An advisor should know when a deadline belongs to your award document rather than repeating a standard exercise-window rule. Use a CPA to model tax obligations, including ordinary income at vest or exercise when applicable and capital gain or loss on a later sale. The <a href="https://www.irs.gov/taxtopics/tc427">IRS overview of stock options</a> distinguishes statutory and nonstatutory treatment.</p>
<h2>Questions that separate planning from a product pitch</h2>
<ol><li>How do you count vested and unvested equity in the household's risk?</li><li>What downside would threaten our goals, and what concentration target follows from that?</li><li>Who reviews trading restrictions, tax and legal documents?</li><li>Which options are feasible now, and what are their after-tax costs?</li><li>How do you charge for the analysis, and would you earn from a proposed product?</li></ol>
<p>Verify the adviser, fees and conflicts using <a href="https://www.investor.gov/introduction-investing/getting-started/working-investment-professional/using-iapd">IAPD</a>. No concentrated-stock specialist is tagged on this page. The profiles below are a general roster; ask each advisor about location, experience and fit. Equity-compensation calculators are illustrations, not personalized tax advice.</p>
''',
}
